name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, lint, build and test
        run: |
          npm install
          npm run lint
          npm run build
          npm run test
